POP_FRAQ$region[POP_FRAQ$location_id == 	33	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	34	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	35	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	36	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	37	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	38	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	39	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	40	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	41	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	43	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	44	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	45	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	46	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	47	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	48	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	50	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	49	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	51	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	52	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	53	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	54	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	55	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	57	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	58	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	59	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	60	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	61	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	62	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	63	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	71	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	72	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	66	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	67	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	68	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	69	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	101	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	349	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	102	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	97	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	98	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	99	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	74	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	75	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	76	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	77	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	78	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	79	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	80	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	81	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	82	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	83	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	84	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	85	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	86	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	87	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	88	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	367	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	89	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	90	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	91	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	396	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	92	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	93	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	94	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	95	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	121	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	122	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	123	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	105	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	106	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	107	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	108	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	305	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	109	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	110	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	111	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	112	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	113	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	114	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	115	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	385	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	393	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	116	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	117	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	118	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	119	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	422	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	125	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	126	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	127	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	128	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	129	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	130	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	131	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	132	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	133	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	135	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	136	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	160	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	139	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	140	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	141	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	142	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	143	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	144	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	145	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	146	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	147	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	148	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	150	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	149	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	151	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	152	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	522	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	153	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	154	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	155	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	156	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	157	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	161	]	=	158
POP_FRAQ$region[POP_FRAQ$location_id == 	162	]	=	158
POP_FRAQ$region[POP_FRAQ$location_id == 	163	]	=	158
POP_FRAQ$region[POP_FRAQ$location_id == 	164	]	=	158
POP_FRAQ$region[POP_FRAQ$location_id == 	165	]	=	158
POP_FRAQ$region[POP_FRAQ$location_id == 	6	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	7	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	8	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	298	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	320	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	22	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	351	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	23	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	24	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	25	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	369	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	374	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	376	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	380	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	26	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	27	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	28	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	413	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	29	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	416	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	30	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	10	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	11	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	12	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	13	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	14	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	183	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	15	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	16	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	186	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	17	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	18	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	19	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	20	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	168	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	169	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	170	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	171	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	172	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	173	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	175	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	176	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	177	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	178	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	179	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	180	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	181	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	182	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	184	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	185	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	187	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	435	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	190	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	189	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	191	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	193	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	197	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	194	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	195	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	196	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	198	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	200	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	201	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	203	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	202	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	204	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	205	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	206	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	207	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	208	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	209	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	210	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	211	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	212	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	213	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	214	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	215	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	216	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	217	]	=	166
POP_FRAQ$region[POP_FRAQ$location_id == 	218	]	=	166


POP_FRAQ$region[POP_FRAQ$location_id == 	31	]	=	31
POP_FRAQ$region[POP_FRAQ$location_id == 	64	]	=	64
POP_FRAQ$region[POP_FRAQ$location_id == 	103	]	=	103
POP_FRAQ$region[POP_FRAQ$location_id == 	137	]	=	137
POP_FRAQ$region[POP_FRAQ$location_id == 	158	]	=	158
POP_FRAQ$region[POP_FRAQ$location_id == 	4	]	=	4
POP_FRAQ$region[POP_FRAQ$location_id == 	166	]	=	166
